# Generated by Django 4.2.2 on 2023-06-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_favorite_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_books',
        ),
    ]
