# Generated by Django 4.2.2 on 2023-06-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_parser', '0003_keyword'),
        ('lib_by_spec', '0001_initial'),
        ('users', '0003_remove_user_favorite_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(through='lib_by_spec.Favorite_book', to='book_parser.book'),
        ),
    ]
