# Generated by Django 4.2.2 on 2023-06-23 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 16, 54, 56, 320822, tzinfo=datetime.timezone.utc)),
        ),
    ]
