# Generated by Django 4.2.2 on 2023-06-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_created',
        ),
    ]
