# Generated by Django 4.2.2 on 2023-06-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline_selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'Ключевое слово', 'verbose_name_plural': 'Ключевые слова'},
        ),
        migrations.AlterField(
            model_name='discipline',
            name='keywords',
            field=models.ManyToManyField(to='discipline_selection.keyword', verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название дисциплины'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='key_phrase',
            field=models.CharField(max_length=128, unique=True, verbose_name='Ключевая фраза'),
        ),
    ]
