# Generated by Django 4.2.2 on 2023-06-20 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.CharField(max_length=256)),
                ('annotation', models.CharField(max_length=2048)),
                ('bibl_record', models.CharField(max_length=1024)),
                ('year_published', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('pages_count', models.IntegerField()),
                ('isbn', models.CharField(max_length=64)),
                ('authors', models.ManyToManyField(to='book_parser.author')),
                ('disciplines', models.ManyToManyField(to='book_parser.discipline')),
            ],
        ),
    ]
