# Generated by Django 4.2.2 on 2023-06-20 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='annotation',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='bibl_record',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
