# Generated by Django 4.2.2 on 2023-06-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_parser', '0002_alter_book_annotation_alter_book_bibl_record_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_phrase', models.CharField(max_length=128)),
                ('disciplines', models.ManyToManyField(to='book_parser.discipline')),
            ],
        ),
    ]
