# Generated by Django 4.2.2 on 2023-06-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_parser', '0003_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='CHANGE_NAME', max_length=256),
            preserve_default=False,
        ),
    ]
