# Generated by Django 4.2.2 on 2023-06-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_parser', '0004_alter_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='disciplines',
        ),
        migrations.AddField(
            model_name='discipline',
            name='keywords',
            field=models.ManyToManyField(to='book_parser.keyword'),
        ),
    ]
