# Generated by Django 4.2.2 on 2023-06-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_parser', '0005_remove_keyword_disciplines_discipline_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='key_phrase',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
