# Generated by Django 4.2.2 on 2023-06-25 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline_selection', '0002_alter_discipline_options_alter_keyword_options_and_more'),
        ('book_parser', '0007_alter_book_disciplines_alter_book_pages_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(max_length=128, unique=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='book',
            name='annotation',
            field=models.CharField(max_length=2048, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='book_parser.author', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bibl_record',
            field=models.CharField(max_length=1024, null=True, verbose_name='Библиографическая запись'),
        ),
        migrations.AlterField(
            model_name='book',
            name='disciplines',
            field=models.ManyToManyField(to='discipline_selection.discipline', verbose_name='Дисциплины'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=64, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(null=True, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages_count',
            field=models.IntegerField(null=True, verbose_name='Страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Год издания'),
        ),
    ]
