# Generated by Django 4.2.2 on 2023-06-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_parser', '0011_alter_book_bibl_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(max_length=150, null=True, upload_to='covers/', verbose_name='Обложка книги'),
        ),
    ]
