# Generated by Django 4.2.7 on 2023-11-18 22:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_parser', '0012_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Год'),
        ),
        migrations.CreateModel(
            name='HistoricalBook',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('link', models.URLField(db_index=True, null=True, verbose_name='Ссылка')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('cover', models.TextField(max_length=150, null=True, verbose_name='Обложка книги')),
                ('annotation', models.CharField(max_length=4096, null=True, verbose_name='Аннотация')),
                ('bibl_record', models.CharField(max_length=2048, null=True, verbose_name='Библиографическая запись')),
                ('year_published', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Год')),
                ('pages_count', models.IntegerField(null=True, verbose_name='Страниц')),
                ('isbn', models.CharField(max_length=64, null=True, verbose_name='ISBN')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Книга',
                'verbose_name_plural': 'historical Книги',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
