# Generated by Django 4.2.2 on 2023-06-22 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lib_by_spec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_book',
            name='time_added',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
