# Generated by Django 4.2.2 on 2023-06-25 12:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_parser', '0008_alter_author_options_alter_book_options_and_more'),
        ('lib_by_spec', '0016_alter_favorite_book_time_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite_book',
            options={'verbose_name': 'Избранная книга', 'verbose_name_plural': 'Избранные книги'},
        ),
        migrations.AlterField(
            model_name='favorite_book',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_parser.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='favorite_book',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 12, 28, 4, 755680, tzinfo=datetime.timezone.utc), verbose_name='Время добаления'),
        ),
        migrations.AlterField(
            model_name='favorite_book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
