# Generated by Django 4.2.2 on 2023-06-25 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_by_spec', '0020_alter_favorite_book_time_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_book',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 15, 16, 43, 226087, tzinfo=datetime.timezone.utc), verbose_name='Время добаления'),
        ),
    ]
